### ISSUE TITLE
Move translations to standard Rails i18n mechanism

### ISSUE THREAD

**Issue by ahankinson** [rism-ch/muscat#1004]
This is an issue to track the progress of a translation clean-up that is underway and ensure visibility of the process across the team. 

Currently the editor uses Muscat-specific format for configuring the field names, where each type of record (Source, Person, Work, etc.) has a complete set of translations for all languages. This has led to divergent translations, and a lot of work for translators as they need to go through each file and translate each key.

The goal of this mini-project is to shift the editor field translations to a more standard Rails i18n configuration mechanism, and to consolidate the translations so that we can better ensure consistency across languages. This means there will  be a central set of translations in the `locales` directory, with a mapping from the MARC editor configurations to a shared unique key in these translations.

For example, we currently have:

```
"246":
  label:
    it: Varianti del titolo diplomatico
    fr: Variante du titre diplomatique
    de: Weiterer diplomatischer Titel
    en: Variant title on source
    pt: "Título variante na fonte"
    es: "Variante de título en fuente"
    pl: Alternatywny tytuł w źródle
  fields:
    a:
      label:
        it: Varianti del titolo diplomatico
        fr: Variante du titre diplomatique
        de: Weiterer diplomatischer Titel
        en: Variant title on manuscript
        pt: "Variante de título na fonte"
        es: "Variante de título en fuente"
        pl: Alternatywny tytuł w rękopisie
      edit_label:
        en: ""
```

This will be centralized and cleaned up (in a spreadsheet), assigning a unique key to each translation:

```
records.variant_ms_title | Variant title on manuscript | Variante du titre diplomatique | Weiterer diplomatischer Titel | Varianti del titolo diplomatico | Variante de título en fuente | Variante de título na fonte | Alternatywny tytuł w rękopisie
---
records.variant_source_title | Variant title on source | Variante du titre diplomatique | Weiterer diplomatischer Titel | Varianti del titolo diplomatico | Variante de título en fuente | Título variante na fonte | Alternatywny tytuł w źródle
```

The mapping will then look like this:

```
"246":
  "fields":
    "a":
      "label": "records.variant_ms_title"
  "label": "records.variant_source_title"
```

This will expand to the value of the "records.variant_ms_title" key in separate translation yml files, e.g., for German a file "de.yml" would have:

```
"de":
  ...
  "records":
      ...
      variant_ms_title: Weiterer diplomatischer Titel
      variant_source_title: Weiterer diplomatischer Titel
```

While "fr.yml" would have:

```
"fr":
  ...
  "records":
    variant_ms_title: Variante du titre diplomatique
    variant_source_title: Variante du titre diplomatique
```

The basic process will be:

- [x] Export all existing translations to a spreadsheet for review
- [x] Review translations and clean up any divergent ones
- [x] Create standard keyed i18n yml files for the translation files (e.g., one per language) from the spreadsheet
- [x] Generate a mapping .yml from the current Muscat field configurations to the standard rails configuration
- [x] Extract translation configurations to a [new repository](https://github.com/rism-digital/translations) where they can be shared among projects

It is anticipated that the translation files will live in the external repository, while the mapping files for Muscat will live in the Muscat repository.

After the cleanup part of the project, new translation keys can be added to deal with places where the same term is not translated the same way across all languages. This will be tracked separately.
