### ISSUE TITLE
New languages for Sources in 041

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#1016]
Could you please add these languages to the drop-down list in Sources (041, all subfields)?

aus - Australian languages
ben - Bengali 
sai - South American Indian (Other)

**Comment by ahankinson** [comment]
@jenniferward do you have translations for these?

**Comment by xhero** [comment]
@ahankinson the translations should be added to the files, right? can I edit them on the repo?

**Comment by xhero** [comment]
I added three labels as

```yml
aus:
  label: languages.australian
ben:
  label: languages.bengali
sai:
  label: languages.south_american
```
which show "translation missing" in the editor, the translations need to be added
