### ISSUE TITLE
Muscat 7.0, file institutions, country codes (43)

### ISSUE THREAD

**Issue by Docudoctor** [rism-ch/muscat#1047]
Dear colleagues,
the country codes (43) in the German version of Muscat are bilingual (German/ English). 
Please correct. :)
Thanks,
Guido

**Comment by xhero** [comment]
Translation team! this is a job for you!

**Comment by jenniferward** [comment]
Aren't those already done? https://github.com/rism-digital/translations/blob/7b446e5dbc587c4ded3f907b5a4e077698911930/locales/pl.yml starting at line 122

**Comment by xhero** [comment]
Isn't the problem in the DE version?

**Comment by jenniferward** [comment]
Spanish looks complete https://github.com/rism-digital/translations/blob/7b446e5dbc587c4ded3f907b5a4e077698911930/locales/es.yml but it is showing up as a blank list in Muscat.

PT looks incomplete (this would be a good candidate for automatic translation to be checked later) but is also showing up as a blank list. Can it default to English?

**Comment by xhero** [comment]
It should say translation_missing not be blank

**Comment by xhero** [comment]
I see now, they are empty in the translation file:
```yml
    austria_carinthia: ''
    austria_lower_austria: ''
    austria_salzburg: ''
    austria_styria: ''
    austria_tyrol: ''
    austria_upper_austria: ''
    austria_vienna: ''
```
