### ISSUE TITLE
Weird top border in editor sidebar

### ISSUE THREAD

**Issue by lpugin** [rism-ch/muscat#561]
![image](https://user-images.githubusercontent.com/689412/34995143-e8a7f4de-fad5-11e7-900e-d7499c283613.png)

**Comment by xhero** [comment]
The culprit is

`	position: fixed;` in the CSS

**Comment by xhero** [comment]
The change comes from jquery, which used to set some defaults:

```css
html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,font,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td{
    margin:0;
    padding:0;
    border:0;
    outline:0;
    font-weight:inherit;
    font-style:inherit;
    font-size:100%;
    font-family:inherit;
    vertical-align:baseline;
}

```

That apparently are not set anymore, adding a margin: 0 to h3 fixes the issue
