### ISSUE TITLE
Change name of field 028

### ISSUE THREAD

**Issue by jenniferward** [rism-ch/muscat#567]
028 in Muscat is currently only for plate numbers, not publisher numbers. 

Please change: PUBLISHER NUMBER (028) to PLATE NUMBER (028)

**Comment by xhero** [comment]
Should this be changed in the other languages also?

```yml
    it: Numero dell'editore
    fr: "Numéro d'éditeur"
    de: Verlagsnummer
```
